#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt -y update
sudo apt -y upgrade
sudo apt install -y nginx
sudo service nginx start
echo "Hello World" | tee /var/www/html/index.html